import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import { Theme } from '@radix-ui/themes';
import NavBar from '@/components/NavBar';
import DeskTopNav from '@/components/DeskTopNav';
const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Instagram',
  description: 'Generated by sam07a',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <Theme>
          {modal}
          <div className="flex">
            <DeskTopNav />
            {children}
          </div>
          <NavBar />
        </Theme>
      </body>
    </html>
  );
}
